# Generated by Django 5.0.2 on 2025-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_manager', '0002_remove_course_code_alter_exam_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(default='Lunes 14a18hs', help_text='Ejemplo: Martes 14a18hs', max_length=100),
        ),
    ]
