# Generated by Django 5.0.2 on 2025-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_manager', '0003_course_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.CharField(help_text='Ejemplo: Martes 14a18hs', max_length=100),
        ),
    ]
