# Generated by Django 5.0.2 on 2025-03-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_manager', '0005_course_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.CharField(help_text='Ejemplo: Martes 14a18hs, Ma14a18, etc.', max_length=100),
        ),
    ]
