# Generated by Django 5.0.2 on 2024-03-01 02:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('number_of_subjects', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('university', models.CharField(max_length=50)),
                ('duration', models.DecimalField(decimal_places=1, help_text='Duración de la carrera en años. Ejemplo: 3.5 (tres años y medio)', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, max_length=300)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_hub.career')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('sub_title', models.CharField(blank=True, max_length=80)),
                ('content', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='blog/subject/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_hub.subject')),
            ],
        ),
    ]
