# Generated by Django 5.0.2 on 2024-03-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, upload_to='study/publication/', verbose_name='<django.db.models.fields.related.ForeignKey>-<django.db.models.fields.DateTimeField>'),
        ),
    ]
