# Generated by Django 5.0.2 on 2024-03-20 05:01

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_hub', '0003_alter_publication_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['career', 'code']},
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, upload_to='publication/', verbose_name='Imagen para tu publicación'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='sub_title',
            field=models.CharField(max_length=80),
        ),
    ]
