# Generated by Django 5.0.2 on 2024-03-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_hub', '0005_remove_publication_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
