# Generated by Django 5.0.2 on 2025-03-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_hub', '0006_remove_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
